---
- name: Install ntp
  yum:
    name=ntp
    state=present

- name: Generate /etc/ntp.conf
  template:
    dest=/etc/ntp.conf
    src=ntp.conf.j2
    owner=root
    group=root
    seuser=system_u
    serole=object_r
    setype=net_conf_t
    mode=0644
  notify: restart ntpd

- name: ntpd service
  service:
    name=ntpd
    state=started
